FROM node:20.11.1-alpine3.19 AS base

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
USER 1001:1001 
RUN mkdir .next
COPY --chown=1001:1001 ./.next/standalone ./
# COPY --chown=1001:1001 ./.next/static ./.next/static
COPY --chown=1001:1001 ./public ./public

USER 1001:1001 
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENTRYPOINT [ "node", "server.js" ]
