networks:
  default:
    name: cr-mongo-net
    external: false

services:
  mongodb:
    image: "mongo:8.0.10"
    container_name: cr-mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default
    volumes:
      - ../data/mongodb/:/data/db:Z
