version: "3.8"

networks:
  default:
    name: cr-mongo
    external: false

services:
  mongodb:
    image: "mongo:8.0.10"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default
    volumes:
      - ./mongodb/:/data/db:Z
