version: "3.8"

networks:
  default:
    name: cr-postgres
    external: false

services:
  postgres:
    image: "postgres:17"
    container_name: cr-postgres
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - default
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data:Z
