version: "3.8"

networks:
  default:
    name: cr-postgres
    external: false

services:
  postgres:
    image: "postgres:17"
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - default
    volumes:
      - ./postgres/:/var/lib/postgresql/data:Z
    ports:
      - "127.0.0.1:5432:5432"
